proxy:
  image: nginx:latest
  container_name: proxy
  restart: always
  ports:
    - "80:80"
  volumes:
    - "/tmp/nginx/conf.d:/etc/nginx/conf.d"
    - "/tmp/log:/var/log"

app:
  image: lifeot/sample-web-ui:latest
  ports:
    - "8080"
  environment:
    - VIRTUAL_HOST=localhost
    - VIRTUAL_PORT=8080
